from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from api.code_writer import CODE_ROOT
from api.memory_storage import remember_project
from api.permissions import evaluate_permission


def create_mern_restaurant_project(user_request: str) -> dict:
    project_name = _project_name(user_request)
    project_dir = CODE_ROOT / f"{datetime.now().strftime('%Y%m%d-%H%M%S')}-{project_name}"
    decision = evaluate_permission("code.generate", f"create MERN project {project_dir}", path=project_dir)
    if not decision.allowed:
        return {"ok": False, "error": decision.message}

    files = _mern_files(user_request)
    for relative, content in files.items():
        path = project_dir / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")

    remember_project(project_dir.name, str(project_dir), f"Generated MERN restaurant workspace for: {user_request}")
    return {
        "ok": True,
        "path": str(project_dir),
        "name": project_dir.name,
        "installCommands": [
            "npm install",
            "npm --prefix frontend install",
            "npm --prefix backend install",
        ],
        "verifyCommands": [
            "npm --prefix frontend run build",
            "npm --prefix backend run check",
        ],
        "devCommand": "npm run dev",
        "previewUrl": "http://127.0.0.1:5173",
    }


def _project_name(user_request: str) -> str:
    lowered = user_request.lower()
    base = "mern-restaurant"
    if "cafe" in lowered:
        base = "mern-cafe"
    if "pizza" in lowered:
        base = "mern-pizza-restaurant"
    return base


def _mern_files(user_request: str) -> dict[str, str]:
    app_title = "Jarvis Table"
    return {
        "package.json": json.dumps(
            {
                "name": "jarvis-mern-restaurant",
                "private": True,
                "scripts": {
                    "dev": "concurrently \"npm --prefix backend run dev\" \"npm --prefix frontend run dev -- --host 127.0.0.1\"",
                    "build": "npm --prefix frontend run build",
                    "check": "npm --prefix frontend run build && npm --prefix backend run check",
                },
                "devDependencies": {"concurrently": "^9.1.2"},
            },
            indent=2,
        ),
        "README.md": f"# MERN Restaurant Website\n\nGenerated by JX Jarvis.\n\nRequest: {user_request}\n\n## Commands\n\n```powershell\nnpm install\nnpm --prefix frontend install\nnpm --prefix backend install\nnpm run dev\n```\n",
        "frontend/package.json": json.dumps(
            {
                "name": "jarvis-restaurant-frontend",
                "private": True,
                "type": "module",
                "scripts": {"dev": "vite", "build": "vite build", "preview": "vite preview --host 127.0.0.1"},
                "dependencies": {"@vitejs/plugin-react": "^4.3.4", "vite": "^6.0.11", "typescript": "^5.7.2", "react": "^19.0.0", "react-dom": "^19.0.0", "lucide-react": "^0.469.0"},
                "devDependencies": {},
            },
            indent=2,
        ),
        "frontend/index.html": '<div id="root"></div><script type="module" src="/src/main.jsx"></script>\n',
        "frontend/src/main.jsx": """import React from "react";
import { createRoot } from "react-dom/client";
import { CalendarDays, ChefHat, ShoppingBag, Star } from "lucide-react";
import "./styles.css";

const menu = [
  { name: "Charcoal Tandoori Platter", price: 18, tag: "Signature", image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=900&q=80" },
  { name: "Malabar Pepper Pasta", price: 15, tag: "Chef pick", image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80" },
  { name: "Saffron Citrus Mocktail", price: 8, tag: "Fresh", image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80" },
];

function App() {
  const [cart, setCart] = React.useState([]);
  const total = cart.reduce((sum, item) => sum + item.price, 0);

  async function reserve(event) {
    event.preventDefault();
    const data = Object.fromEntries(new FormData(event.currentTarget));
    const response = await fetch("/api/reservations", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });
    const result = await response.json();
    alert(result.message);
    event.currentTarget.reset();
  }

  return (
    <main>
      <nav><ChefHat /><strong>""" + app_title + """</strong><a href="#menu">Menu</a><a href="#reserve">Reserve</a></nav>
      <section className="hero">
        <div>
          <p className="eyebrow">Modern MERN dining</p>
          <h1>Restaurant experiences with live menu ordering and reservations.</h1>
          <p>Polished React frontend, Express API, Mongo-ready data layer, responsive UI, and booking flow.</p>
          <a className="cta" href="#menu">Explore menu</a>
        </div>
      </section>
      <section className="stats">
        <span><Star /> 4.9 guest rating</span><span><CalendarDays /> Same-day bookings</span><span><ShoppingBag /> Live cart total: ${total}</span>
      </section>
      <section id="menu" className="menu">
        {menu.map((item) => (
          <article key={item.name}>
            <img src={item.image} alt={item.name} />
            <div><span>{item.tag}</span><h2>{item.name}</h2><p>${item.price}</p><button onClick={() => setCart([...cart, item])}>Add to cart</button></div>
          </article>
        ))}
      </section>
      <section id="reserve" className="reserve">
        <form onSubmit={reserve}>
          <h2>Reserve a table</h2>
          <input name="name" placeholder="Name" required />
          <input name="email" type="email" placeholder="Email" required />
          <input name="partySize" type="number" min="1" max="12" placeholder="Party size" required />
          <button>Book table</button>
        </form>
      </section>
    </main>
  );
}

createRoot(document.getElementById("root")).render(<App />);
""",
        "frontend/src/styles.css": """*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#101010;color:#fff}nav{height:70px;display:flex;align-items:center;gap:22px;padding:0 6vw;background:#111;border-bottom:1px solid #2a2a2a;position:sticky;top:0;z-index:3}nav svg{color:#ffb347}nav a{color:#ddd;text-decoration:none}.hero{min-height:72vh;display:grid;align-items:center;padding:6vw;background:linear-gradient(90deg,rgba(0,0,0,.78),rgba(0,0,0,.28)),url('https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1800&q=85') center/cover}.hero div{max-width:780px}.eyebrow{color:#ffb347;text-transform:uppercase;letter-spacing:.16em}.hero h1{font-size:clamp(42px,7vw,86px);line-height:.95;margin:0 0 22px}.hero p{max-width:650px;color:#e7e0d7;font-size:19px}.cta,button{border:0;border-radius:8px;background:#ffb347;color:#15100b;font-weight:800;padding:13px 18px;text-decoration:none;cursor:pointer}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;padding:24px 6vw;background:#181818}.stats span{display:flex;align-items:center;gap:10px;border:1px solid #333;border-radius:8px;padding:16px}.menu{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;padding:6vw}.menu article{border:1px solid #333;border-radius:8px;overflow:hidden;background:#181818}.menu img{width:100%;height:230px;object-fit:cover}.menu div{padding:20px}.menu span{color:#ffb347}.reserve{padding:6vw;background:#f5efe5;color:#16110c}.reserve form{max-width:680px;margin:auto;display:grid;gap:14px}.reserve input{height:48px;border:1px solid #d6c8b8;border-radius:8px;padding:0 14px;font-size:16px}@media(max-width:800px){.stats,.menu{grid-template-columns:1fr}.hero{min-height:64vh}}""",
        "backend/package.json": json.dumps(
            {
                "name": "jarvis-restaurant-backend",
                "private": True,
                "type": "module",
                "scripts": {"dev": "node server.js", "check": "node --check server.js"},
                "dependencies": {"cors": "^2.8.5", "dotenv": "^16.4.7", "express": "^4.21.2", "mongoose": "^8.9.5"},
            },
            indent=2,
        ),
        "backend/server.js": """import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import mongoose from "mongoose";

dotenv.config();
const app = express();
const port = process.env.PORT || 5174;
app.use(cors());
app.use(express.json());

const reservationSchema = new mongoose.Schema({
  name: String,
  email: String,
  partySize: Number,
  createdAt: { type: Date, default: Date.now },
});
const Reservation = mongoose.models.Reservation || mongoose.model("Reservation", reservationSchema);

app.get("/api/health", (_req, res) => res.json({ ok: true, service: "restaurant-api" }));
app.post("/api/reservations", async (req, res) => {
  const payload = req.body || {};
  if (!payload.name || !payload.email || !payload.partySize) {
    return res.status(400).json({ message: "Missing reservation details." });
  }
  if (process.env.MONGODB_URI) {
    if (mongoose.connection.readyState === 0) await mongoose.connect(process.env.MONGODB_URI);
    await Reservation.create(payload);
  }
  return res.json({ message: `Table reserved for ${payload.name}.` });
});

app.listen(port, () => console.log(`Restaurant API running on http://127.0.0.1:${port}`));
""",
        "frontend/vite.config.js": """import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: { "/api": "http://127.0.0.1:5174" },
  },
});
""",
        ".env.example": "MONGODB_URI=mongodb://127.0.0.1:27017/jarvis_restaurant\nPORT=5174\n",
    }
