from agents.base import AgentResult, BaseAgent
from planner.engine import PlanStep, TaskState
from reports.generator import VulnerabilityFinding, write_bug_bounty_report


class ReportAgent(BaseAgent):
    name = "report"

    def run(self, step: PlanStep, state: TaskState) -> AgentResult:
        recon = state.artifacts.get("recon") or {}
        target = str(state.artifacts.get("target") or recon.get("target") or "target")
        raw_findings = recon.get("findings") or []
        findings = [
            VulnerabilityFinding(
                title=str(item.get("title") or "Potential finding"),
                severity=str(item.get("severity") or "Informational"),
                affected_asset=str(item.get("affected_asset") or target),
                evidence=str(item.get("evidence") or ""),
                reproduction_steps=list(item.get("reproduction_steps") or []),
                impact=str(item.get("impact") or "Requires manual validation."),
                remediation=str(item.get("remediation") or "Apply standard hardening and validate access controls."),
                cvss=str(item.get("cvss") or "Not calculated"),
            )
            for item in raw_findings
            if isinstance(item, dict)
        ]
        report = write_bug_bounty_report(target, findings, notes=[f"Generated by {self.name}."])
        state.artifacts["report"] = report
        return AgentResult(True, f"Report generated: {report['path']}", report)
